### ISSUE TITLE
Main Emitter flashes when leaving lockout with 3C or when locking while main is off.

### ISSUE THREAD

**Issue by webshadow** [starryalley/Anduril2#16]
Leaving lockout with 3C flashes main emitter. Since the purpose is to leave main off after unlocking it is a little irritating. When locking while main is off this happens too. Since we can have AUX/Button show the lockout status i think it's redundant to indicate with main and another chance to blind yourself could be elliminated. To still have the confirmation even if Aux is configured the same in locked/nonlocked state, Aux could be flashed instead of main.

**Comment by starryalley** [comment]
By looking at the code, 4C from off: 
```
    // 4 clicks: soft lockout
    else if (event == EV_4clicks) {
        blink_once();
        set_state(lockout_state, 0);
        return MISCHIEF_MANAGED;
    }
```

3C from locked:
```
    // 3 clicks: exit and turn off
    else if (event == EV_3clicks) {
        blink_once();
        set_state(off_state, 0);
        return MISCHIEF_MANAGED;
    }
```

It's default Anduril2 behaviour. While the blinking doesn't bother me that much, I kind of agree with you the blinking isn't necessary and blinking AUX may be better. I'll see what I can do.
