### ISSUE TITLE
TS10, misc menu (9H from off) not working

### ISSUE THREAD

**Issue by kubrick89** [starryalley/Anduril2#2]
Hi,
I'm using the latest release and it seems to me that 9H menu is not working so I'm not able to enable the startup mode. Am I missing something?

**Comment by starryalley** [comment]
Hi @kubrick89 sorry the startup mode was added after the latest release. This does remind me of making another release. I'll do that later today! Thanks to trying out.

**Comment by starryalley** [comment]
Hi @kubrick89 I just created another [release](https://github.com/starryalley/Anduril2/releases/tag/release_20220919)
Please give it a try. Thanks!

**Comment by kubrick89** [comment]
Yep, now is there and working. Thanks a lor for your work
