### ISSUE TITLE
Wurkkos TS11 / TS25 support

### ISSUE THREAD

**Issue by tri4ng1e** [starryalley/Anduril2#24]
Hello!

Is it possible to add Wurkkos TS11 / TS25 support? They seem to share the same firmware, code `0715`. I found the config file [here](http://bazaar.launchpad.net/~gabe/flashlight-firmware/anduril2/view/head:/ToyKeeper/spaghetti-monster/anduril/cfg-wurkkos-ts25.h?sort=filename) and hwdef [here](https://bazaar.launchpad.net/~gabe/flashlight-firmware/anduril2/view/head:/ToyKeeper/hwdef-Wurkkos_TS25.h).

I do have TS11 (NLD today) shipped with version 2022-07-25-0715, but I don't have a probe yet. I ordered one from Hank, and I can help with testing when it arrives.

Thank you!

**Comment by starryalley** [comment]
Yes I can include the build however I won't be able to test it as I don't plan to buy TS11/TS25 any time soon. But it looks like TS11/TS25 is T1616 so the flashing kit from Hank won't work on them?

**Comment by starryalley** [comment]
Please give it a try. It's a direct copy and compile. If everything works fine I'll include in the next release.

[anduril.wurkkos-ts25.hex.zip](https://github.com/starryalley/Anduril2/files/11247051/anduril.wurkkos-ts25.hex.zip)

**Comment by tri4ng1e** [comment]
Thank you!

If I understood correctly, Hank's probe will do, and the flasher I already have. I will try the build right after receiving the parcel. But I'm afraid it will be quite a long time to wait. Maybe I'll try without the probe.

**Comment by SiteRelEnby** [comment]
The t1616 uses a different protocol for flashing it with the 3 pins. In the US you can get the 3-pin flashing adapter from gchart on BLF ($5 each and $4 shipping), or from thefreeman in europe.

https://budgetlightforum.com/t/adventures-in-tinyavr-1-series/55911/322

**Comment by dirtymoustache** [comment]
> Please give it a try. It's a direct copy and compile. If everything works fine I'll include in the next release.
> 
> [anduril.wurkkos-ts25.hex.zip](https://github.com/starryalley/Anduril2/files/11247051/anduril.wurkkos-ts25.hex.zip)

Just wanted to add that this appears to work perfectly fine on my TS25.

**Comment by tri4ng1e** [comment]
Thank you! Good news.

My parcel is still in transit (in fact, it's the second parcel from Hank, but it's a whole another story), hoping to get it in 1.5-2 weeks or so.

**Comment by tri4ng1e** [comment]
@starryalley 
Finally, I received my parcel from Hank. As expected, I was able to flash TS11 with his probe and USB-UART module I already had. Happy to report that all functions seem to work well!

**Comment by starryalley** [comment]
Thank you for the update. I've also included TS25 hex in the latest release here https://github.com/starryalley/Anduril2/releases/tag/release_20230614
