### ISSUE TITLE
Exchanging patches

### ISSUE THREAD

**Issue by SammysHP** [starryalley/Anduril2#4]
Hi and thanks for your contributions!

I've noticed that you're linking some of my patches. I suggest that you link this page instead as commits might become outdated and I try to keep this page updated: https://github.com/SammysHP/flashlight-firmware/wiki/Modifications-Overview

**Comment by starryalley** [comment]
Hey @SammysHP thanks for your contribution to the flashlight world. I appreciate your high quality work in your Anduril2 repo. Of course. I'll update all my references to your repo with that page!
